name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"


      # New step: Use access token instead of password
      - name: Get Docker Access Token
        run: echo "${{ secrets.DOCKER_ACCESS_TOKEN }}" > ~/.docker/config.json

      - name: Build Docker image
        run: docker build -t your-image-name .

      - name: Push Docker image
        run: docker push your-image-name
